name = "ZeroToML"
uuid = "92d4436d-aade-4fb1-9591-dec7c909cb55"
authors = ["Demetrius Michael <arrrwalktheplank@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
